# Generated by Django 3.0.2 on 2020-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pupdate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
